In [6]:
import pandas as pd

In [54]:
df = pd.DataFrame({"cliente": ["Ana", "Bruno", "Carlos", "Diego", "Ester"],
                   "idade": [35, 22, 63, 59, 25],
                   "cartoes": [3, 2, 1, 1, 4],
                   "renda": [35000, 50000, 200000, 170000, 40000],
                   "calote": [0, 1, 0, 0, 1]
                   })

In [46]:
df

cliente  idade  cartoes   renda  calote
0     Ana     35        3   35000       0
1   Bruno     22        2   50000       1
2  Carlos     63        1  200000       0
3   Diego     59        1  170000       0
4   Ester     25        4   40000       1

In [56]:
import numpy as np

x_alvo = np.array([37.0, 2.0, 50000.0])

In [57]:
x_alvo

array([3.7e+01, 2.0e+00, 5.0e+04])

In [11]:
import math


def euclidiana(x1, x2):

    dist = 0

    for i in range(0, len(x1)):

        dist += (x1[i] - x2[i])**2

    return math.sqrt(dist)

In [58]:
x1 = df.drop(columns=["cliente", "calote"]).iloc[0].values

In [59]:
x1

array([   35,     3, 35000])

# Normalização dos atributos


In [67]:
for i in df.drop(columns=["cliente", "calote"]).columns:

    df[i] = (df[i].max() - df[i]) / df[i].min()

In [64]:
x_alvo

array([3.7e+01, 2.0e+00, 5.0e+04])

In [65]:
x_alvo[0] = (df.idade.max() - x_alvo[0]) / df.idade.min()
x_alvo[1] = (df.cartoes.max() - x_alvo[1]) / df.cartoes.min()
x_alvo[2] = (df.renda.max() - x_alvo[2]) / df.renda.min()

In [66]:
x_alvo

array([1.18181818, 2.        , 4.28571429])

In [31]:
df

cliente     idade  cartoes     renda  calote
0     Ana  1.272727      1.0  4.714286       0
1   Bruno  1.863636      2.0  4.285714       1
2  Carlos  0.000000      3.0  0.000000       0
3   Diego  0.181818      3.0  0.857143       0
4   Ester  1.727273      0.0  4.571429       1

In [68]:

for i in range(0, len(df)):

    x = df.drop(columns=["cliente", "calote"]).iloc[i]

    print(x, '\n')

    print(euclidiana(x, x_alvo), '\n')

idade      1.272727
cartoes    1.000000
renda      4.714286
Name: 0, dtype: float64 

1.0917590998923126 

idade      1.863636
cartoes    2.000000
renda      4.285714
Name: 1, dtype: float64 

0.6818181818181817 

idade      0.0
cartoes    3.0
renda      0.0
Name: 2, dtype: float64 

4.556757745771827 

idade      0.181818
cartoes    3.000000
renda      0.857143
Name: 3, dtype: float64 

3.7087871387849054 

idade      1.727273
cartoes    0.000000
renda      4.571429
Name: 4, dtype: float64 

2.0926426628113672 

