In [1]:
import pandas as pd

In [50]:
df = pd.read_csv('mammographic_masses.csv', na_values= '?', names=['BI_RADS', 'Age', 'Shape', 'Margin', 'Density', 'Classe'])

In [51]:
df

BI_RADS   Age  Shape  Margin  Density  Classe
0        5.0  67.0    3.0     5.0      3.0       1
1        4.0  43.0    1.0     1.0      NaN       1
2        5.0  58.0    4.0     5.0      3.0       1
3        4.0  28.0    1.0     1.0      3.0       0
4        5.0  74.0    1.0     5.0      NaN       1
..       ...   ...    ...     ...      ...     ...
956      4.0  47.0    2.0     1.0      3.0       0
957      4.0  56.0    4.0     5.0      3.0       1
958      4.0  64.0    4.0     5.0      3.0       0
959      5.0  66.0    4.0     5.0      3.0       1
960      4.0  62.0    3.0     3.0      3.0       0

[961 rows x 6 columns]

In [3]:
df2 = df.fillna(0)

In [4]:
df2

BI_RADS   Age  Shape  Margin  Density  Classe
0        5.0  67.0    3.0     5.0      3.0       1
1        4.0  43.0    1.0     1.0      0.0       1
2        5.0  58.0    4.0     5.0      3.0       1
3        4.0  28.0    1.0     1.0      3.0       0
4        5.0  74.0    1.0     5.0      0.0       1
..       ...   ...    ...     ...      ...     ...
956      4.0  47.0    2.0     1.0      3.0       0
957      4.0  56.0    4.0     5.0      3.0       1
958      4.0  64.0    4.0     5.0      3.0       0
959      5.0  66.0    4.0     5.0      3.0       1
960      4.0  62.0    3.0     3.0      3.0       0

[961 rows x 6 columns]

In [99]:
from sklearn.model_selection import train_test_split

X = df2.drop(columns=['Classe'])
y = df2.Classe

X_treino, X_teste, y_treino, y_teste = train_test_split(X, y, test_size=0.5, random_state=12)

In [100]:
from sklearn.naive_bayes import GaussianNB

In [101]:
clf = GaussianNB()
clf.fit(X_treino, y_treino)

GaussianNB()

In [102]:
# clf.predict(X_teste)

In [103]:
# clf.predict_proba(X_teste)

In [104]:
clf.score(X_teste, y_teste)

0.814968814968815

In [78]:
X_teste.iloc[0:3]

BI_RADS   Age  Shape  Margin  Density
746      5.0  69.0    4.0     4.0      3.0
201      3.0  49.0    4.0     4.0      3.0
946      4.0  57.0    2.0     4.0      3.0

In [79]:
import numpy as np
clf.predict_proba(X_teste.iloc[0:3])

array([[0.01953305, 0.98046695],
       [0.10236596, 0.89763404],
       [0.66604648, 0.33395352]])

In [80]:
clf.predict(X_teste.iloc[0:3])

array([1, 1, 0])

In [81]:
df.Classe.value_counts()

0    516
1    445
Name: Classe, dtype: int64

In [82]:
516/len(df)

0.5369406867845994

In [83]:
clf.class_prior_

array([0.51788491, 0.48211509])

In [84]:
clf.theta_

array([[ 3.95795796, 49.42342342,  1.96096096,  1.78378378,  2.56756757],
       [ 4.84516129, 61.99354839,  3.40322581,  3.68064516,  2.80645161]])

In [85]:
from sklearn import tree

clf2 = tree.DecisionTreeClassifier(max_depth=2)
clf2 = clf2.fit(X_treino, y_treino)

In [86]:
clf2.score(X_teste, y_teste)

0.7735849056603774